### ISSUE TITLE
Compatibility with OL4

### ISSUE THREAD

**Issue by hunt3ri** [jonataswalker/ol3-geocoder#120]
Hi

We're working on a new build of the HOT tasking manager which we've building on OL4. 

https://github.com/hotosm/tasking-manager

We've integrated the latest build of the ol3-geocoder, but can see there's one or two compatibility problems, that you appear to have addressed in master but have yet to release.  Any idea on a rough schedule for a new build to npm?

Many thanks
Iain

**Comment by jonataswalker** [comment]
Hi @hunt3ri, v2.5.0 released and published.

Have a good day.

**Comment by hunt3ri** [comment]
Awesome, thanks for the super quick turnaround.  Hugely appreciated 💯
