### ISSUE TITLE
closing search bar

### ISSUE THREAD

**Issue by dddesign** [jonataswalker/ol3-geocoder#13]
hey jonatas, great plugin!

this case is working:
I open the searchbar > type keywords > hit enter > the result is showing up > I dont select one of the result but instead I click outside of results > results and searchbar is hiding

this one not:
I open the searchbar > I dont type anything but want to close the searchbar again > I click outside of searchbar > nothing happens but I expect that the searchbar is hiding... (to hide I have to click the icon again)

I would be great if the searchbar would hide if I click outside of it, in any case...

thanks jan

**Comment by jonataswalker** [comment]
Good catch! Fixed with #14.
