### ISSUE TITLE
Google Maps Geocoder support allowed?

### ISSUE THREAD

**Issue by ThomasG77** [jonataswalker/ol3-geocoder#16]
It's technically simple to geocode using Google Maps Geocoder.

However, according to Google [terms of use](https://developers.google.com/maps/documentation/geocoding/usage-limits#terms-of-use-restrictions), we are not really allowed to use it outside Google Maps API but your library support it.

You should mention it somewhere so if people use it, it's not your concern.

**Comment by jonataswalker** [comment]
Yeah, you're right. We are clearly not allowed to use it.

I just saw [others](https://github.com/perliedman/leaflet-control-geocoder) using and implemented it. Well, they're not a real open-source friend, are they? :disappointed:

Thanks for your alert.
