### ISSUE TITLE
Feature Request: Limit search to a country

### ISSUE THREAD

**Issue by hamiltoncj** [jonataswalker/ol3-geocoder#18]
I was wondering if it would be possible to limit the geocoding search results to a particular country or set of countries like the US and Canada? I would probably use 'osm' or possibly 'photon' or any of the services that has a free service.

**Comment by jonataswalker** [comment]
Yes, it is possible, but only (for now) with `osm` or `mapquest`. Photon doesn't provide a country filter see https://github.com/komoot/photon/issues/175.

I'll let you know when I have any progress.

**Comment by jonataswalker** [comment]
It will be used a [ISO_3166-1 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).

**Comment by jonataswalker** [comment]
@hamiltoncj please see #23
