### ISSUE TITLE
Allow more projections

### ISSUE THREAD

**Issue by joseahr** [jonataswalker/ol3-geocoder#20]
Hi! I had to rewrite your code to use the Geocoder in my map's View projection (EPSG:4258). It would be great that Geocoder takes the projection from the map's View instead of using 'to3857' function.

**Comment by jonataswalker** [comment]
Absolutely. I'll let you know when I fix this. Thanks @joseahr .

**Comment by joseahr** [comment]
I'll be waiting for updates =) 
Thank you too!

**Comment by jonataswalker** [comment]
@joseahr v1.5.2 released.

See #22
