### ISSUE TITLE
Outdated ol3-geocoder.min.css in CDN

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [jonataswalker/ol3-geocoder#27]
http://cdn.jsdelivr.net/openlayers.geocoder/latest/ol3-geocoder.min.css is not minified version of
http://cdn.jsdelivr.net/openlayers.geocoder/latest/ol3-geocoder.css and classes don't match those generated in HTML.

**Comment by jonataswalker** [comment]
@jan-tosovsky-cz  Would you mind to capture some screenshots?

For me is everything just fine.

**Comment by jan-tosovsky-cz** [comment]
It is indeed strange. At work I could see the correct version, but on my home computer there is an obsolete one (in both FF and Chrome), even after deleting browser cache.

![image](https://cloud.githubusercontent.com/assets/3907898/14829400/72edfc82-0beb-11e6-80da-fcb4ccc899ae.png)

Looking at that suspicious CF-Cache-Status: HIT response attribute I think it could be caused by an obsolete cache served by a specific local CDN server.

**Comment by jonataswalker** [comment]
Let's consider this a cache/proxy issue, ok? I can be solved on your side.

Feel free to reopen it if you have any further problem related.
