### ISSUE TITLE
Use Other Projection e.g.: EPSG:31370 (other than ESPG: 4326/3857)

### ISSUE THREAD

**Issue by NicolasBel** [jonataswalker/ol3-geocoder#28]
Hi,

I have been able to use the Geocoder with the EPSG:4326 projection (great initiative :-) ).
However, my main OL viewer is using another projection system (for Belgium: e.g. EPSG:31370). Therefore, I’m not able to get the zooming extent and the pin at the right location. Any location I type always gives me the same wrong location at the bottom left of my viewer.
 
As my projection system has to be in Lambert 72 (i use WMS and other services with the same projection), I have added this in my main OL html page (allows displaying all my layers in a good way):
`// Set LAMBERT PROJECTION - EPSG 31370 
var belgianProjection = new ol.proj.Projection({
                code: 'EPSG:31370',
                extent: [14637.25, 22608.21,291015.29 ,246424.28],
                units: 'm'
                               });
ol.proj.addProjection(belgianProjection);`

I went through the ol3-geocoder-debug.js file, I have tried to modify several lines associated to the projection/coordinates:
e.g. Added this section
`                  to31370: function to31370(coord) {
                    return ol.proj.transform(
                      [parseFloat(coord[0]), parseFloat(coord[1])],
                      'EPSG:4326', 'EPSG:31370'
                    );`

But still the same result.

Does someone have any idea to solve this? It would be highly appreciated. 
Many thanx in advance for the precious help.

Nicolas B
Geo-ICT Consultant

**Comment by jonataswalker** [comment]
Hi @NicolasBel 

Actually ol3-geocoder is projection agnostic. It transforms the coordinates from geocoding Provider &mdash; `EPSG:4326` &mdash; to `ol.View` projection.

I've made [this fiddle](http://jsfiddle.net/jonataswalker/qhss2404/) for you, please take a look.

I'm loading `http://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.14/proj4.js` and defining this projection according to [epsg.io](http://epsg.io):

```js
proj4.defs("EPSG:31370","+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=-106.869,52.2978,-103.724,0.3366,-0.457,1.8422,-1.2747 +units=m +no_defs");
```

**Comment by NicolasBel** [comment]
Thank you so much!
Adding the proj4 definition proj4...

`defs("EPSG:31370","+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=-106.869,52.2978,-103.724,0.3366,-0.457,1.8422,-1.2747 +units=m +no_defs");`

solved everything :-)

Best regards,

Nicolas
