### ISSUE TITLE
How to build the plugin?

### ISSUE THREAD

**Issue by gnatih** [jonataswalker/ol3-geocoder#47]
I need to make a few changes to the plugin, which will require me to rebuild the minified script. Can you add build instructions to the Readme? Specifically I am looking to add the final zoom level (resolution) as an option when initiating the geocoder.

**Comment by jonataswalker** [comment]
Hey @gnatih, you make changes in `src/js/*` and then `make build`, you can also tell [`Makefile`](https://github.com/jonataswalker/ol3-geocoder/blob/master/Makefile) to watch for changes and build automatically with `make build-watch`.

The most used targets:
```bash
# to build JS
$ make build-js
# to build CSS/SASS
$ make build-css
# to build both
$ make build
# to build and watch
$ make build-watch
# to test - CasperJS
$ make test
# to build and test
$ make ci
```

**Comment by jonataswalker** [comment]
I guess I'll add a new method. Something like `preventDefault()` to be used with:

```javascript
geocoder.on('addresschosen', function(evt) {
  geocoder.preventDefault();
  // add your own fly function
});
```

What do you think? Does it satisfy your needs?

**Comment by gnatih** [comment]
Then the geocoder will not zoom, pan or add the location marker, right?

**Comment by jonataswalker** [comment]
Yes, will do nothing, it will be all up to you.

**Comment by gnatih** [comment]
Sounds good.  And I should also thank you for the plugin or your quick responses.

**Comment by jonataswalker** [comment]
So @gnatih I guess this is fixed with #49. Feel free to reopen this ticket if there's anything missing.

**Comment by harry-wood** [comment]
On the original question, can you spell this out to me a little more. I'm new to nodejs, but also trying build/rebuild the 'dist' contents. I'm just seeing
```
$ make build
make: Nothing to be done for 'build'.
$ make
make: *** No targets specified and no makefile found.  Stop.
```
I guess that's trying to invoke GNU Make, which I guess is not the right thing?

**Comment by walkermatt** [comment]
@harry-wood Hi, I've been doing a bit of work on the the plugin lately and I've been invoking the `npm` scripts directly:

    npm run build

You can see the available script in `package.json` under the `scripts` property.

**Comment by harry-wood** [comment]
Thanks. Easy when you know how!
