### ISSUE TITLE
Add Bing Map support

### ISSUE THREAD

**Issue by Vbahole** [jonataswalker/ol3-geocoder#51]
Is there a way to geocode using a Bing key?

**Comment by jonataswalker** [comment]
Hey @Vbahole currently there's no support to Bing API but it can be done. Is this a must for you? Have you seen the other providers?

**Comment by Vbahole** [comment]
I was able to copy and modify the google provider to work for Bing.  In order to get it to work i cloned and modified your json utils method to use a jQuery ajax call with a jsonp callback. It seems Bing does not support CORS so i was getting a cross domain issue. It is working well now.

**Comment by jonataswalker** [comment]
Bing provider added - #52.

v2.2.0 released.
