### ISSUE TITLE
Triggering Search

### ISSUE THREAD

**Issue by ojsdude** [jonataswalker/ol3-geocoder#56]
I have seen that it is possible to listen to the `addresschosen` event for when a user has selected a place, but I wondered how I could replicate the user pressing `Enter` when having typed something. I want to:
1 Update the result as the user types.
2 Replicate a user action for a tutorial feature on the website I am working on.
It would be nice to be able to trigger an event.

**Comment by ojsdude** [comment]
I have had a look at the code and I think I am looking for a way to run the `query` function.

**Comment by jonataswalker** [comment]
I'm almost there, there'll be a `autocomplete` option (boolean).

Hang tight.

**Comment by ojsdude** [comment]
Fantastic :smiley:

**Comment by jonataswalker** [comment]
@ojsdude please take a look at [v2.3.0](https://github.com/jonataswalker/ol3-geocoder/releases/tag/2.3.0) just released.

```javascript
  var geocoder = new Geocoder('nominatim', {
    provider: 'photon',
    autoComplete: true,
    autoCompleteMinLength: 3
  });
```

**Comment by ojsdude** [comment]
Will this be on the latest CDN soon?

**Comment by ojsdude** [comment]
This is a great feature, but I don't believe it adresses my issue. Auto completion works while the user is typing but I want the query to be submitted when jQuery has input a value too. I am trying to create automation of tasks using an API.

**Comment by jonataswalker** [comment]
So, you have (and trying to use it) `<input>` other than ol3-geocoder created?

**Comment by ojsdude** [comment]
no, I have tried to trigger a `keydown` event and `input` event on the `input#gcd-input.ol3-geocoder-input-search` but they do not seem to trigger the `query` or `autoComplete` functions at all.

**Comment by jonataswalker** [comment]
I can trigger query with this:

```javascript
    var input = document.getElementById('gcd-input');
    var evt = new CustomEvent('keydown');
    evt.which = evt.keyCode = 13;
    input.dispatchEvent(evt);
```

**Comment by ojsdude** [comment]
I thought I had tried that, but it seems to work. That's perfect, thanks a lot.

**Comment by jonataswalker** [comment]
CDN caching is about 7 days (which is a lot) but you can use a version tag like:

https://cdn.jsdelivr.net/openlayers.geocoder/2.3.0/ol3-geocoder.js
