### ISSUE TITLE
Remove map layer

### ISSUE THREAD

**Issue by sclose** [jonataswalker/ol3-geocoder#61]
I'd like to remove the map layer (or even the features within the existing map layer) created by this geocoder.  In working through this code, I've extended the prototype to include a removeLayer function, but am having difficulty calling this function from the same button listener that collapses/expands the search.  Thoughts?

**Comment by jonataswalker** [comment]
@sclose Set the geocoder layer invisible, wouldn't be enough?

```javascript
geocoder.getLayer().setVisible(false);
```

**Comment by jonataswalker** [comment]
You can also use `preventDefault: false` on constructor. No panning and no feature.

**Comment by sclose** [comment]
actually, 
`geocoder.getLayer().getSource().clear();` 
was what I was looking for, and completely overlooked doing this external to the control!  thanks for the insight.
