### ISSUE TITLE
form-Element for searchbox necessary?

### ISSUE THREAD

**Issue by Equalizer7** [jonataswalker/ol3-geocoder#79]
Hello.

Just wanted to ask if there is any design reason for using a form to surround the searchbox?
If you want to embed a map with your geocoder in an existing form, this will cause problems as nested forms are invalid HTML and jquery.validate floods the console with errors.

I replaced the line **`'<form id="'+ form_id +'" action="javascript:void(0);">',`** with **`'<div id="'+ form_id +'">',`** to test and it seems to not cause any problems so far

Best regards.

**Comment by jonataswalker** [comment]
Hey @Equalizer7,

Let me think about it, perhaps it's more problematic than useful.

**Comment by jonataswalker** [comment]
`<form>` removed with #109
