### ISSUE TITLE
Support for Pelias

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [jonataswalker/ol3-geocoder#8]
It would be nice to add https://github.com/pelias/pelias geocoding service to the list of geocoders.

**Comment by jonataswalker** [comment]
Really nice @jan-tosovsky-cz. I'll take a look.

**Comment by jonataswalker** [comment]
Done, see #10.

**Comment by jan-tosovsky-cz** [comment]
Wow, amazing job! Thanks a lot.
