### ISSUE TITLE
The zoom button focus get left on

### ISSUE THREAD

**Issue by bwyss** [jonataswalker/ol3-geocoder#85]
The zoom button focus get left on when you click to zoom

<img width="160" alt="zoom" src="https://cloud.githubusercontent.com/assets/340159/19788897/3cb3e824-9c60-11e6-9fce-c108c8d0402b.png">

**Comment by jonataswalker** [comment]
I'm afraid you'll have to describe a bit more of what's happening.

**Comment by bwyss** [comment]
Hi, sorry for that.
Wow, I just realized that this is an openlayers 3 issue and not introduced by the geocoder.

The issue description: when you click to zoom, each click event on the zoom button will make the zoom button show the 'focus' (a blue border around the button). The focus should not persist after the click event IMHO.

This has a bad effect with the geocoder, when you click to open the geocoder the focus is off, and then when you click a second time to close the geocoder the focus is then left on. IIHO this is incorrect.

I will take up this issue with openlayers.

Cheers

**Comment by jonataswalker** [comment]
Hmm, weird! Maybe a fiddle would help.

Closing for now.

**Comment by bwyss** [comment]
Just figured it out, just need to add this to your css to make things right:

.ol-control button:focus {
    text-decoration: none;
    background-color: <color of your choice>;
}
