### ISSUE TITLE
Google request now needs to be https

### ISSUE THREAD

**Issue by odavidbrito** [jonataswalker/ol3-geocoder#91]
Jonatas Walker great work!

Just needed to change the Google provider url to 
url:"https://maps.googleapis.com/maps/api/geocode/json"
instead of 
url:"//maps.googleapis.com/maps/api/geocode/json"

and worked like a charm.

Thanks a lot!

Ah also added on the event listener 'addresschosen', a function to remove previous markers so they do not pile up.
It can be called from the listener with the current marker coordinates and will remove all ol3-geocoer markers with different coordinates, or for instance from a 'moveend' listener without coordinates (zoom change or drag) and will wipeout all ol3-geocoder markers.
Maybe someone may find it useful:

`function removeGeocoderFeatures(coord) {

    map.getLayers().forEach(function (lyr) {
        if (lyr.get('name') != undefined && lyr.get('name').startsWith('geocoder-layer-')) {

            //vector layer
            var source = lyr.getSource();

            if (coord === undefined)
                source.clear();
            else {
                source.getFeatures().forEach(function (feat) {
                    //point feature
                    var featCoord = feat.getGeometry().getCoordinates();

                    if (featCoord[0] != coord[0] && featCoord[1] != coord[1])
                        source.removeFeature(feat);
                })
            }
        }
    });
}`

**Comment by odavidbrito** [comment]
Mislooked your methods getLayer and getSource. much simpler!

**Comment by jonataswalker** [comment]
Closing then!

**Comment by jonataswalker** [comment]
@odavidbrito Please see #143
