### ISSUE TITLE
Google Search API

### ISSUE THREAD

**Issue by ibnbay99** [jonataswalker/ol3-geocoder#94]
How i can get/access value using Google Search API:
- postal code on address_components?

thanks

**Comment by jonataswalker** [comment]
You can access the original API response with:
```javascript
geocoder.on('addresschosen', function(evt){
    console.info(evt.address.original);
  });
```

**Comment by ibnbay99** [comment]
How to get value from "types" : [ "postal_code"?:
"address_components" : [            
            {
               "long_name" : "94043",
               "short_name" : "94043",
               "types" : [ "postal_code" ]
            }
         ],
I try evt.address.original.postal_code, but undefined

Thanks

**Comment by ibnbay99** [comment]
Sorry double Post...
I found evt.address.details.postcode.

**Comment by jonataswalker** [comment]
@ibnbay99 Can we close this?

**Comment by ibnbay99** [comment]
@jonataswalker, sure.
Thank you....

**Comment by jonataswalker** [comment]
@ibnbay99 Please see #143
