### ISSUE TITLE
Here Map support

### ISSUE THREAD

**Issue by gonself** [jonataswalker/ol3-geocoder#96]
Is there a way to use "Here api geocoding" with ol3-geocoder? or is in todo list?

i'm modify the ol3-geocoder-debug.js but i think it's no a good idea...

**Comment by jonataswalker** [comment]
Have you tried Bing API? Is there a real difference?

**Comment by gonself** [comment]
Yes, i used Bing or Google, but now we have to use Here for licensing issues...

**Comment by jonataswalker** [comment]
I see. I'll try to implement this new provider as soon as possible. Ok?

**Comment by gonself** [comment]
Ok. Don't be in a hurry, for the moment im use my own ol3-geocoder-debug.js.

Thanks in advanced, if you need some information you can tell me.

**Comment by jonataswalker** [comment]
Well, you could come up with a PR for this provider. That'd be great.

**Comment by gonself** [comment]
hi,
I did the pull request. This is the first time I use github, sorry if there is something wrong...

For implement de Here api we need two "keys", app_id and app_code, i decided to send together joined by # under the 'key' option...

tell me if i need to change something, and one more time sorry if something is wrong

**Comment by jonataswalker** [comment]
Closing this issue since #98 is closed.
